<script setup>
import { computed } from 'vue'
import { menuDishes } from '../lib/menu'
import { AppButton } from './ui'
const props = defineProps({ menu: Object, summary: Object, busy: Boolean })
const emit = defineEmits(['add', 'edit', 'remove', 'availability'])
const rows = computed(() => {
  const dishes = menuDishes(props.menu)
  return [...dishes.map(dish => ({ ...dish, summary: props.summary.orderedDishes.find(row => row.menuItemId ? row.menuItemId === dish.id : row.name === dish.name) })), ...props.summary.orderedDishes.filter(row => !dishes.some(dish => row.menuItemId ? row.menuItemId === dish.id : row.name === dish.name)).map(row => ({ name: row.name, legacy: true, summary: row }))]
})
const money = value => value == null ? 'Chưa có giá' : new Intl.NumberFormat('vi-VN').format(value) + 'đ'
</script>
<template><section class="stack"><div class="row-wrap"><h3 class="section-title">Theo món</h3><AppButton class="spacer" variant="ghost" :disabled="busy || menu.is_closed" @click="emit('add')">+ Thêm món</AppButton><slot name="actions" /></div><p v-if="menu.is_closed" class="meta">Mở lại menu trước khi chỉnh món hoặc đặt hộ.</p><p v-if="!rows.length" class="meta">Menu chữ chưa có món được đặt. Số suất sẽ được tổng hợp từ các đơn.</p><article v-for="(dish,index) in rows" :key="dish.id || index" class="dish-row"><div class="dish-heading"><div><strong>{{ dish.name }}</strong><p class="meta">{{ money(dish.price ?? dish.summary?.unitPrice) }} / suất · {{ dish.available === false ? 'Hết món' : 'Còn nhận đơn' }}</p></div><div class="dish-quantity"><strong>{{ dish.summary?.servings || 0 }}</strong><span class="meta">suất</span></div><div class="dish-total"><strong>{{ dish.summary?.unknownPriceCount ? money(dish.summary.knownTotal) + ' đã biết' : money(dish.summary?.knownTotal ?? (dish.price == null ? null : 0)) }}</strong><p v-if="dish.summary?.unknownPriceCount" class="meta">{{ dish.summary.unknownPriceCount }} suất chưa có giá</p></div></div><div v-if="!dish.legacy" class="row-wrap"><AppButton variant="ghost" :disabled="busy || menu.is_closed" @click="emit('edit',dish)">Sửa món</AppButton><AppButton variant="ghost" :disabled="busy || menu.is_closed" @click="emit('availability',dish,dish.available === false)">{{ dish.available === false ? 'Nhận đặt lại' : 'Báo hết món' }}</AppButton><AppButton variant="ghost" :disabled="busy || menu.is_closed || !!dish.summary?.servings" @click="emit('remove',dish)">Xóa món</AppButton></div><details v-if="dish.summary?.people.length"><summary>{{ dish.summary.people.length }} người đặt</summary><p v-for="person in dish.summary.people" :key="person.orderId" class="meta">{{ person.name }}<span v-if="person.note"> · {{ person.note }}</span></p></details></article></section></template>
<style scoped>.dish-row{padding:1rem 0;border-top:1px solid var(--line);display:grid;gap:.75rem}.dish-heading{display:grid;grid-template-columns:minmax(0,1fr) 80px minmax(120px,.4fr);gap:1rem;align-items:center}.dish-heading strong{overflow-wrap:anywhere}.dish-quantity{display:grid;text-align:center}.dish-quantity strong{font-size:1.75rem}.dish-total{text-align:right}summary{min-height:44px;align-content:center;cursor:pointer;font-size:.875rem}@media(max-width:600px){.dish-heading{grid-template-columns:minmax(0,1fr) 60px}.dish-total{grid-column:1/-1;text-align:left}.dish-row .row-wrap{gap:.5rem}}</style>
