<script setup>
import { computed } from 'vue'
import { menuDishes } from '../lib/menu'
import { AppButton } from './ui'
const props = defineProps({ menu: Object, summary: Object, busy: Boolean })
const emit = defineEmits(['add', 'edit', 'remove', 'availability'])
const rows = computed(() => {
  const dishes = menuDishes(props.menu)
  return [...dishes.map(dish => ({ ...dish, summary: props.summary.orderedDishes.find(row => row.menuItemId ? row.menuItemId === dish.id : row.name === dish.name) })), ...props.summary.orderedDishes.filter(row => !dishes.some(dish => row.menuItemId ? row.menuItemId === dish.id : row.name === dish.name)).map(row => ({ name: row.name, legacy: true, summary: row }))]
})
const money = value => value == null ? 'Chưa có giá' : new Intl.NumberFormat('vi-VN').format(value) + 'đ'
</script>
<template>
  <div class="dish-list"><p v-if="menu.is_closed" class="manage-warning">Mở lại menu trước khi chỉnh món hoặc đặt hộ.</p><p v-if="!rows.length" class="empty-dishes">Menu chữ chưa có món được đặt. Số suất sẽ được tổng hợp từ các đơn.</p><table v-else class="dish-table"><thead><tr><th>Món</th><th>Số suất</th><th>Giá / suất</th><th>Thao tác</th></tr></thead><tbody><tr v-for="(dish,index) in rows" :key="dish.id || index"><td><strong class="dish-name">{{ dish.name }}</strong><span v-if="dish.available===false" class="status-badge">Hết món</span><details v-if="dish.summary?.people.length" class="dish-people"><summary>{{ dish.summary.people.map(person=>person.name).join(', ') }} · Xem ghi chú</summary><ul><li v-for="person in dish.summary.people" :key="person.orderId">{{ person.name }} — {{ person.note || 'Không có ghi chú' }}</li></ul></details><p v-else class="meta">Chưa ai đặt</p></td><td><span class="dish-quantity">{{ dish.summary?.servings || 0 }}</span></td><td>{{ money(dish.price ?? dish.summary?.unitPrice) }}<p class="line-total meta">Tổng dòng: {{ dish.summary?.unknownPriceCount ? money(dish.summary.knownTotal)+' đã biết' : money(dish.summary?.knownTotal ?? (dish.price == null ? null : 0)) }}</p><p v-if="dish.summary?.unknownPriceCount" class="meta">{{ dish.summary.unknownPriceCount }} suất chưa có giá</p></td><td><div v-if="!dish.legacy" class="dish-actions"><AppButton variant="ghost" :disabled="busy || menu.is_closed" @click="emit('edit',dish)">Sửa</AppButton><AppButton variant="ghost" :disabled="busy || menu.is_closed" @click="emit('availability',dish,dish.available===false)">{{ dish.available===false ? 'Còn món' : 'Hết món' }}</AppButton><span v-if="dish.summary?.servings" class="meta ordered-note">Đã có đơn</span><AppButton v-else variant="ghost" :disabled="busy || menu.is_closed" @click="emit('remove',dish)">Xóa</AppButton></div><p v-else class="meta">Món nhập từ đơn cũ</p></td></tr></tbody></table></div>
</template>
<style scoped>
.dish-table{width:100%;border-collapse:collapse;margin-top:17px;table-layout:fixed}.dish-table th{text-align:left;font-size:12px;font-weight:650;color:var(--muted);padding:11px 10px;border-bottom:1px solid var(--line)}.dish-table td{padding:17px 10px;border-bottom:1px solid var(--line);vertical-align:top;font-size:14px;overflow-wrap:anywhere}.dish-table th:first-child{width:36%}.dish-table th:nth-child(2){width:12%}.dish-table th:nth-child(3){width:19%}.dish-table th:last-child{width:33%}.dish-name{font-size:14px}.dish-quantity{font-size:25px;line-height:1.3;font-weight:750}.dish-actions{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.dish-actions :deep(.btn){padding:8px 10px;font-size:12px;min-height:44px;border-radius:12px}.dish-people summary{cursor:pointer;min-height:44px;align-content:center;font-size:12px;color:var(--muted)}.dish-people ul{padding-left:17px;font-size:12px;color:var(--ink-soft);line-height:1.7;margin:0}.status-badge{display:inline-flex;padding:4px 8px;margin-left:5px;border-radius:7px;font-size:11px;font-weight:650;background:var(--bg-tint);color:var(--muted);white-space:nowrap}.dish-table .meta{font-size:12px;line-height:1.6;margin:7px 0}.ordered-note{align-self:center}.manage-warning{padding:13px;border-left:3px solid var(--line-strong);background:var(--bg-tint);font-size:12px;color:var(--muted);margin:17px 0}.empty-dishes{padding:28px 12px;text-align:center;color:var(--muted);font-size:14px}@media(max-width:640px){.dish-table,.dish-table tbody,.dish-table tr,.dish-table td{display:block;width:100%}.dish-table thead{display:none}.dish-table tr{padding:15px 0;border-top:1px solid var(--line)}.dish-table tr:first-child{border-top:0}.dish-table td{padding:4px 0;border:0}.dish-table td:nth-child(2){display:flex;align-items:baseline;gap:7px}.dish-table td:nth-child(2)::after{content:'suất đã đặt';font-size:12px;color:var(--muted)}.dish-table td:nth-child(3)::before{content:'Giá / suất: ';font-size:12px;color:var(--muted)}.dish-actions{margin-top:8px;gap:8px}.dish-actions :deep(.btn){font-size:13px;padding:9px 13px}}
</style>
