<script setup>
import { ref, computed, watch, nextTick } from 'vue'
import { menuDishes, parseMenuNote } from '../lib/menu'
import { managedOrderAmount } from '../lib/manage-summary'
import { AppDialog, AppButton, FormErrorSummary } from './ui'
const props = defineProps({ open:Boolean, menu:Object, profiles:{type:Array,default:()=>[]}, busy:Boolean, error:String })
const emit = defineEmits(['close','submit'])
const recipient = ref(''), selected = ref([]), text = ref(''), note = ref(''), review = ref(false), errors = ref([]), summary = ref(null)
const dishes = computed(() => menuDishes(props.menu))
const structured = computed(() => !!props.menu?.menu_items?.length || !!parseMenuNote(props.menu?.note))
const availableProfiles = computed(() => props.profiles.filter(profile => !(props.menu?.orders || []).some(order => order.user_id === profile.id)))
const recipientName = computed(() => availableProfiles.value.find(p => p.id === recipient.value)?.full_name || 'Chưa đặt tên')
const chosen = computed(() => dishes.value.filter((dish,index) => selected.value.includes(dish.id || String(index))))
const payload = computed(() => ({user_id:recipient.value, item_text:structured.value ? chosen.value.map(d => d.name).join('\n') : text.value.trim(), note:note.value.trim() || null, ...(structured.value && chosen.value.every(d => d.id) ? {menu_item_ids:chosen.value.map(d => d.id)} : {})}))
const total = computed(() => managedOrderAmount(props.menu, { ...payload.value, order_items: chosen.value.every(d => d.id) ? chosen.value.map(d => ({menu_item_id:d.id})) : [] }))
const money = value => value == null ? 'Chưa có giá' : new Intl.NumberFormat('vi-VN').format(value) + 'đ'
watch(() => props.open, open => { if (open) { recipient.value=''; selected.value=[]; text.value=''; note.value=''; review.value=false; errors.value=[] } })
async function check() {
  errors.value=[]
  if (!recipient.value || !availableProfiles.value.some(p => p.id === recipient.value)) errors.value.push({fieldId:'delegate-recipient',message:'Chọn người chưa có đơn trong menu.'})
  if (!payload.value.item_text) errors.value.push({fieldId:structured.value ? 'delegate-dishes' : 'delegate-text',message:structured.value ? 'Chọn ít nhất một món.' : 'Nhập món cần đặt.'})
  if (props.menu?.is_closed) errors.value.push({fieldId:'delegate-recipient',message:'Menu đã chốt. Mở lại trước khi đặt hộ.'})
  if (errors.value.length) { await nextTick(); summary.value?.focus(); return }
  review.value=true
}
function close() { if (props.busy) return; if ((recipient.value || selected.value.length || text.value || note.value) && !confirm('Bỏ đơn đặt hộ đang nhập?')) return; emit('close') }
</script>
<template><AppDialog :open="open" title="Đặt hộ" @close="close"><div class="stack delegation-content"><FormErrorSummary ref="summary" :errors="errors" /><p v-if="error" class="alert" role="alert">{{ error }}</p><template v-if="!review"><label class="field">Người nhận đơn<select id="delegate-recipient" v-model="recipient" class="input" :aria-invalid="errors.some(e=>e.fieldId==='delegate-recipient')" :disabled="busy"><option value="">Chọn người</option><option v-for="profile in availableProfiles" :key="profile.id" :value="profile.id">{{ profile.full_name || 'Chưa đặt tên' }}</option></select><span v-for="entry in errors.filter(e=>e.fieldId==='delegate-recipient')" :key="entry.message" class="field-error">{{ entry.message }}</span></label><p class="meta">Chỉ thêm đơn mới cho người chưa có đơn trong menu.</p><fieldset v-if="structured" id="delegate-dishes" class="delegate-dishes" tabindex="-1"><legend>Chọn món</legend><label v-for="(dish,index) in dishes" :key="dish.id || index" class="delegate-dish"><input v-model="selected" type="checkbox" :value="dish.id || String(index)" :disabled="busy || dish.available === false" /><span>{{ dish.name }}<span v-if="dish.available === false" class="meta"> · Hết món</span></span><strong>{{ money(dish.price) }}</strong></label><p v-for="entry in errors.filter(e=>e.fieldId==='delegate-dishes')" :key="entry.message" class="field-error">{{ entry.message }}</p></fieldset><label v-else class="field">Món cần đặt<textarea id="delegate-text" v-model="text" class="textarea" :aria-invalid="errors.some(e=>e.fieldId==='delegate-text')" rows="3" :disabled="busy" /><span v-for="entry in errors.filter(e=>e.fieldId==='delegate-text')" :key="entry.message" class="field-error">{{ entry.message }}</span></label><label class="field">Ghi chú<textarea v-model="note" class="textarea" rows="2" maxlength="1000" :disabled="busy" /></label></template><template v-else><div><h3 class="section-title">{{ recipientName }}</h3><p class="meta">{{ menu?.restaurant?.name || menu?.title }}</p></div><p class="order-lines">{{ payload.item_text }}</p><p v-if="note" class="meta">{{ note }}</p><strong>Tổng: {{ total === null ? 'Chưa đủ giá để tính tổng' : money(total) }}</strong><p class="meta">Đơn thuộc {{ recipientName }}. Người nhận tự xác nhận đã trả và đánh giá.</p></template></div><template #footer><AppButton variant="ghost" :disabled="busy" @click="review ? review=false : close()">{{ review ? 'Quay lại sửa' : 'Hủy' }}</AppButton><AppButton v-if="!review" :disabled="busy" @click="check">Xem lại đơn</AppButton><AppButton v-else :loading="busy" @click="emit('submit',payload)">Đặt hộ</AppButton></template></AppDialog></template>
<style scoped>.delegation-content .field{font-size:13px;gap:7px;margin:8px 0}.delegation-content .input,.delegation-content .textarea{min-height:46px;font-size:14px;border-radius:12px;padding:11px 12px}.delegation-content>.meta{font-size:12px;line-height:1.7}.delegation-content h3{font-size:17px}.delegation-content .order-lines{font-size:14px}.delegation-content .delegate-dishes legend{font-size:14px}@media(max-width:640px){.delegation-content .input,.delegation-content .textarea{font-size:16px}}.field-error{color:var(--unpaid-ink);font-size:.875rem}.delegate-dishes{border:0;padding:0;min-width:0}.delegate-dishes legend{font-weight:600;margin-bottom:.5rem}.delegate-dish{display:flex;align-items:center;gap:.75rem;padding:.75rem 0;min-height:44px;border-bottom:1px solid var(--line)}.delegate-dish span{flex:1;overflow-wrap:anywhere}.delegate-dish strong{font-size:.875rem}.delegate-dish input{width:20px;height:20px;accent-color:var(--primary)}.order-lines{white-space:pre-line}</style>
