<script setup>
import { computed, ref } from 'vue'
import { groupOutstandingOrders } from '../lib/manage-summary'
import { formatVNDate } from '../lib/date'
import { AppButton, Spinner } from './ui'
const props = defineProps({ orders: { type:Array, default:()=>[] }, period:String, loading:Boolean, error:String, hasMore:Boolean, totalCount:Number, stale:Boolean, menuId:String })
const emit = defineEmits(['period-change','load-more','open-menu','retry'])
const search = ref(''), sort = ref('oldest')
const groups = computed(() => groupOutstandingOrders(props.menuId ? props.orders.filter(order=>order.menu?.id===props.menuId) : props.orders).filter(group => group.name.toLocaleLowerCase('vi').includes(search.value.toLocaleLowerCase('vi'))).sort((a,b) => sort.value === 'amount' ? b.knownTotal - a.knownTotal : a.oldestDate.localeCompare(b.oldestDate)))
const knownTotal = computed(() => groups.value.reduce((sum, group) => sum + group.knownTotal, 0))
const unknown = computed(() => groups.value.reduce((sum, group) => sum + group.unknownAmountCount, 0))
const money = value => value == null ? 'Chưa có giá' : new Intl.NumberFormat('vi-VN').format(value) + 'đ'
</script>
<template><section class="stack"><div class="ledger-periods" role="group" aria-label="Khoảng ngày chưa thu"><AppButton v-for="option in [{id:'all',name:'Tất cả'},{id:'today',name:'Hôm nay'},{id:'recent',name:'30 ngày trước'},{id:'older',name:'Trước 30 ngày'}]" :key="option.id" variant="ghost" :aria-pressed="period === option.id" @click="emit('period-change',option.id)">{{ option.name }}</AppButton></div><div class="ledger-filters"><label class="field">Tìm người<input v-model="search" type="search" class="input" /></label><label class="field">Sắp xếp<select v-model="sort" class="input"><option value="oldest">Bữa cũ nhất</option><option value="amount">Số tiền đã biết</option></select></label></div><p v-if="menuId" class="meta">Đang xem các khoản của menu trong đường dẫn. <AppButton variant="ghost" to="/dashboard">Tất cả menu</AppButton></p><p v-if="stale" class="meta" role="status">Đang giữ kết quả của khoảng trước cho đến khi tải được khoảng mới.</p><p class="meta" role="status">{{ loading ? 'Đang cập nhật · ' : '' }}{{ orders.length }}{{ totalCount != null ? ' / ' + totalCount : '' }} khoản đã tải{{ hasMore ? ' · Số liệu, tìm kiếm và sắp xếp theo phần đã tải' : '' }}.</p><p v-if="error" class="alert" role="alert">{{ error }} <AppButton variant="ghost" @click="emit('retry')">Thử lại</AppButton></p><Spinner v-if="loading && !orders.length" /><p v-else-if="!groups.length" class="meta">Chưa có khoản chưa trả trong khoảng này.</p><details v-for="group in groups" :key="group.userId" class="ledger-group"><summary><strong>{{ group.name }}</strong><span>{{ group.count }} khoản · {{ money(group.knownTotal) }}{{ group.unknownAmountCount ? ' đã biết' : '' }}</span><span class="meta">Bữa cũ nhất {{ formatVNDate(group.oldestDate) }}<span v-if="group.unknownAmountCount"> · {{ group.unknownAmountCount }} khoản chưa có giá</span></span></summary><article v-for="order in group.entries" :key="order.id" class="ledger-entry"><div><strong>{{ formatVNDate(order.menu?.menu_date) }} · {{ order.menu?.restaurant?.name || order.menu?.title }}</strong><p class="order-lines">{{ order.item_text }}</p><p v-if="order.note" class="meta">{{ order.note }}</p></div><div><strong>{{ money(order.amount) }}</strong><AppButton variant="ghost" @click="emit('open-menu',order.menu.id)">Mở menu</AppButton></div></article></details><div class="row-wrap"><strong>Tổng {{ hasMore ? 'phần đã tải' : 'khoản hiển thị' }}: {{ money(knownTotal) }}</strong><span v-if="unknown" class="meta">{{ unknown }} khoản chưa có giá</span><AppButton v-if="hasMore && !stale" class="spacer" variant="ghost" :loading="loading" @click="emit('load-more')">Tải tiếp</AppButton></div><p class="meta">Trạng thái do mỗi người tự xác nhận trong app. Các khoản cũ vẫn được giữ.</p></section></template>
<style scoped>.ledger-periods{display:flex;gap:.5rem;flex-wrap:wrap}.ledger-periods [aria-pressed=true]{border-color:var(--ink);font-weight:700}.ledger-filters{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,.5fr);gap:1rem}.ledger-group{border:1px solid var(--line);border-radius:var(--radius-sm)}summary{display:grid;gap:.35rem;padding:1rem;cursor:pointer;min-height:44px}.ledger-entry{display:flex;justify-content:space-between;gap:1rem;padding:1rem;border-top:1px solid var(--line)}.ledger-entry>div{min-width:0}.ledger-entry>div:last-child{display:grid;justify-items:end;align-content:start;gap:.5rem}.order-lines{white-space:pre-line;overflow-wrap:anywhere}@media(max-width:600px){.ledger-filters{grid-template-columns:1fr}.ledger-entry{flex-direction:column}.ledger-entry>div:last-child{justify-items:start}}</style>
