<script setup>
import { formatVNDate } from '../lib/date'
import { AppDialog, AppButton } from './ui'
defineProps({ open:Boolean, restaurantName:String, menuDate:String, dishes:Array, note:String, imagePreview:String, posting:Boolean, errors:String, collectorName:{type:String,default:'Bạn'} })
const emit = defineEmits(['close','publish'])
const money = value => value == null ? 'Chưa có giá' : new Intl.NumberFormat('vi-VN').format(value) + 'đ'
</script>
<template><AppDialog :open="open" title="Xem lại menu" @close="emit('close')"><section class="post-review-content"><div class="review-heading"><span class="eyebrow">Xem lại trước khi đăng</span><h3 class="section-title">{{ restaurantName || 'Chưa ghi nhận quán' }}</h3><p class="meta">{{ formatVNDate(menuDate) }}</p></div><div v-if="dishes !== null" class="stack-sm"><div v-for="(dish,index) in dishes" :key="index" class="row-wrap preview-dish"><strong>{{ dish.name }}</strong><span class="spacer">{{ money(dish.price) }}</span></div></div><img v-if="imagePreview" :src="imagePreview" alt="Ảnh thực đơn sẽ đăng" class="preview-image" /><p v-if="note" class="note">{{ note }}</p><div class="review-collector"><span>Người thu tiền</span><strong>{{ collectorName }}</strong></div><p class="review-note">Mọi người tự xác nhận đã trả. Bạn có thể chốt đơn trong Quản lý.</p><p v-if="errors" class="alert" role="alert">{{ errors }}</p></section><template #footer><AppButton variant="ghost" :disabled="posting" @click="emit('close')">Quay lại sửa</AppButton><AppButton :loading="posting" @click="emit('publish')">Đăng menu</AppButton></template></AppDialog></template>
<style scoped>.post-review-content{display:grid;gap:16px}.review-heading h3{font-size:22px;line-height:1.4;margin:8px 0}.review-heading>.meta{font-size:13px}.preview-dish{font-size:14px}.review-collector{display:flex;justify-content:space-between;border-top:1px solid var(--line);padding-top:13px;font-size:14px}.review-note{font-size:12px;color:var(--muted);border-left:3px solid var(--line-strong);padding-left:11px;line-height:1.7}.post-review-content :deep(.eyebrow){font-size:12px;letter-spacing:1px}.preview-dish{padding:.75rem 0;border-bottom:1px solid var(--line)}.preview-dish strong{overflow-wrap:anywhere}.preview-image{width:100%;max-height:300px;object-fit:contain}.note{white-space:pre-line;overflow-wrap:anywhere}</style>
